medium/urls.py
from django.urls import path
from medium import views

app_name = 'medium'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('register/', views.register_user, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('new/', views.NewPostView.as_view(), name='new'),
    path('new2/', views.new_post, name='new2'),
    path('follow/<author_pk>/<int:post_pk>',
         views.follow_user, name='follow_user'),
    path('unfollow/<author_pk>/<int:post_pk>',
         views.unfollow_user, name='unfollow_user'),
    path('follow/topic/<tag>', views.follow_topic, name='follow_topic'),
    path('unfollow/topic/<tag>', views.unfollow_topic, name='unfollow_topic'),

    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post'),
    path('search/', views.SearchListView.as_view(), name='search'),
    path('post/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post/<int:pk>/cheer/', views.add_cheer, name='add_cheer'),
    path('post/<int:pk>/remove_cheer/', views.remove_cheer, name='remove_cheer'),
    path('<int:pk>/', views.ProfileDetailView.as_view(), name='profile'),

    path('post/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('tags/<tag>', views.TagsListView.as_view(), name='tags'),

    path('post/<int:pk>/comment/delete',
         views.delete_comment, name='delete_comment'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),

    path('me/edit/', views.profile_edit, name='me_edit'),
    path('me/drafts/', views.DraftsListView.as_view(), name='drafts'),

    path('me/', views.my_profile, name='me'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medium.urls')),
    re_path(r'^froala_editor/', include('froala_editor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medium/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from django.db.models import Q
from django.core.paginator import Paginator

from taggit.managers import TaggableManager
from froala_editor.fields import FroalaField

# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE, related_name='profile')
    bio = models.TextField(blank=True)
    avatar = models.ImageField(
        upload_to='avatars', default='avatars/default-profile.png')
    followed_topics = TaggableManager(blank=True)

    following = models.ManyToManyField(
        'self', related_name='follows', symmetrical=False, blank=True)

    # def followed_topics_as_list(self):
    #     return self.followed_topics.split(',')

    # def followed_users_as_list(self):
    #     return self.followed_users.split(',')

    def recent_posts(self):
        return Post.objects.filter(author=self.user).order_by('-published_date')[:10]

    def recent_comments(self):
        return Comment.objects.filter(author=self.user).order_by('-created_date')[:10]

    def recent_cheers(self):
        return Post.objects.filter(cheers__in=[self.user])[:10]

    def followed_posts(self):
        topics = self.followed_topics.all()
        followed_users = self.following.all()
        print(followed_users)
        q_objects = Q()
        # TODO FIX THIS
        if topics.count() >= 1:
            for topic in topics:
                q_objects.add(Q(tags__name__in=[topic]), Q.OR)
        print(q_objects)

        if followed_users.count() >= 1:
            for user in followed_users:
                q_objects.add(Q(author=user.user), Q.OR)
        print(q_objects)

        if q_objects:
            posts = Post.objects.filter(
                q_objects).distinct().order_by(('-published_date'))
            print(posts)
            return posts
        else:
            return False

    def paginated_followed_posts(self):
        return Paginator(self.followed_posts(), 10)

    def __str__(self):
        return str(self.user)


class FeaturedImage(models.Model):
    image = models.ImageField(upload_to='posts', blank=True)


class Topic(models.Model):
    tags = models.CharField(max_length=200, blank=True, unique=True)

    def __str__(self):
        return self.tags


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,)
    title = models.CharField(max_length=200)
    content = FroalaField()
    featured_image = models.ImageField(
        upload_to='posts', blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    tags = TaggableManager(blank=True)
    cheers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="post_cheers", symmetrical=False, blank=True)

    def author_string(self):
        return str(self.author)

    def all_comments(self):
        return self.comments.all().order_by('-created_date')

    def __str__(self):
        return self.title

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('medium:post', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,)
    content = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post', kwargs={
            'pk': self.pk
        })

medium/forms.py
from django import forms
from django.contrib.auth.models import User
from medium.models import UserProfile, Post, Comment
from crispy_forms.helper import FormHelper
from mediumeditor.widgets import MediumEditorTextarea
from froala_editor.widgets import FroalaEditor


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password', 'confirm_password',
                  'email', 'first_name', 'last_name')

    def clean(self):
        cleaned_data = super(UserForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "passwords do not match"
            )
    helper = FormHelper()


class UserEditForm(forms.ModelForm):

    class Meta():
        model = User
        fields = (
            'email', 'first_name', 'last_name')

    helper = FormHelper()


class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields = ('bio', 'avatar')
    helper = FormHelper()


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('title', 'tags', 'content', 'featured_image')

        widgets = {
            'title': forms.Textarea(attrs={'class': 'post-title-input', 'placeholder': 'Title'}),
            'content': FroalaEditor(),
        }


class PostFeaturedImageForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('featured_image',)


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('content',)

    helper = FormHelper()

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].label = "Write a response"

medium/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.utils import timezone
from django.core.paginator import Paginator
from itertools import chain
import re

from medium.forms import (UserForm, UserProfileForm, PostForm,
                          UserEditForm, PostFeaturedImageForm, CommentForm)
from medium.models import Post, UserProfile, Comment, Topic, User
# Create your views here.


class IndexView(generic.ListView):
    template_name = 'medium/index.html'
    context_object_name = 'posts_list'
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a Queryset
        if self.request.user.is_authenticated:
            posts = self.request.user.profile.followed_posts()
            if posts:
                context['followed_posts'] = posts[:10]
        return context


class TagsListView(generic.ListView):
    template_name = 'medium/topic_list.html'
    context_object_name = 'posts_list'

    def get_queryset(self):
        return Post.objects.filter(tags__name__in=[self.kwargs['tag']])

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet
        context['tag'] = self.kwargs['tag']
        return context


class DraftsListView(generic.ListView):
    template_name = 'medium/drafts.html'
    context_object_name = 'posts_list'

    def get_queryset(self):
        return Post.objects.filter(published_date=None, author=self.request.user)


class SearchListView(generic.ListView):
    template_name = 'medium/search.html'
    context_object_name = 'posts_list'
    paginate_by = 10

    def get_queryset(self):
        search = self.request.GET.get('search')
        return Post.objects.filter(Q(published_date__lte=timezone.now()),
                                   Q(title__contains=search) | Q(content__contains=search)).order_by('-published_date')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet
        context['search'] = self.request.GET.get('search')
        return context


class NewPostView(LoginRequiredMixin, generic.CreateView):
    login_url = '/login/'
    redirect_field_name = 'medium/post.html'
    template_name = 'medium/new_post.html'
    form_class = PostForm
    model = Post

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, generic.DeleteView):
    login_url = '/login/'
    model = Post
    success_url = reverse_lazy('medium:index')


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'medium/post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context


class ProfileDetailView(generic.DetailView):
    model = User
    context_object_name = 'medium_user'
    template_name = 'medium/profile.html'


class PostEditView(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    redirect_field_name = 'medium/post.html'
    template_name = 'medium/new_post.html'
    form_class = PostForm
    model = Post


def add_comment(request, pk):
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = Post.objects.get(pk=pk)
            comment.author = request.user
            comment.save()
    return HttpResponseRedirect(reverse('medium:post', kwargs={'pk': pk}))


def my_profile(request):
    return render(request, 'medium/me.html', {'medium_user': request.user})


def register_user(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and user_profile_form.is_valid():
            new_user = user_form.save()
            new_user.set_password(new_user.password)
            new_user.save()

            new_user_profile = user_profile_form.save(commit=False)
            new_user_profile.user = new_user

            if 'avatar' in request.FILES:
                new_user_profile.avatar = request.FILES['avatar']

            new_user_profile.save()
            registered = True
        else:
            print(user_form.errors, user_profile_form.errors)
    else:
        user_form = UserForm()
        user_profile_form = UserProfileForm()
    return render(request, 'medium/registration.html', {
        'user_form': user_form,
        'user_profile_form': user_profile_form,
        'registered': registered
    })


def new_post(request):

    if request.method == 'POST':
        post_form = PostForm(data=request.POST)
        post_featured_image_form = PostFeaturedImageForm(data=request.POST)
        if post_form.is_valid() and post_featured_image_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()

            if 'featured_image' in request.FILES:

                post.avatar = request.FILES['featured_image']
                post.save()

    else:
        post_form = PostForm()
        post_featured_image_form = PostFeaturedImageForm()

    return render(request, 'medium/new_post.html', {
        'form': post_form,
        'featured_form': post_featured_image_form,

    })

# TODO make this a cbv or base it off of the pagenated view


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('medium:index'))
        else:
            return HttpResponse('invalid login details')
    else:
        return render(request, 'medium/login.html')


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return HttpResponseRedirect(reverse('medium:post', kwargs={'pk': pk}))


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('medium:index'))


@login_required
def profile_edit(request):

    if request.method == 'POST':
        user_form = UserEditForm(data=request.POST, instance=request.user)
        user_profile_form = UserProfileForm(
            data=request.POST, instance=request.user.profile)
        user_form.save()
        user_profile = user_profile_form.save()

        if 'avatar' in request.FILES:
            user_profile.avatar = request.FILES['avatar']
        user_profile.save()

        return HttpResponseRedirect(reverse('medium:me_edit'))
    else:
        user_form = UserEditForm(instance=request.user)
        user_profile_form = UserProfileForm(instance=request.user.profile)
        return render(request, 'medium/profile_edit.html', {
            'user_profile_form': user_profile_form,
            'user_form': user_form,
        })


@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('medium:post', pk=post_pk)


@login_required
def follow_user(request, author_pk, post_pk):
    user = UserProfile.objects.get(user=request.user)
    print(user)
    # user.followed_users += str(author) + ','
    follow = UserProfile.objects.get(user=author_pk)
    print(follow)
    user.following.add(follow)
    user.save()
    return redirect('medium:post', pk=post_pk)
    # followed_users += user + ', '


@login_required
def unfollow_user(request, author_pk, post_pk):
    user = UserProfile.objects.get(user=request.user)
    print(user)
    # user.followed_users += str(author) + ','
    follow = UserProfile.objects.get(user=author_pk)
    print(follow)
    user.following.remove(follow)
    user.save()
    return redirect('medium:post', pk=post_pk)
    # followed_users += user + ', '


@login_required
def follow_topic(request, tag):
    user = UserProfile.objects.get(user=request.user)
    user.followed_topics.add(tag)
    user.save()
    return redirect('medium:tags', tag=tag)


@login_required
def unfollow_topic(request, tag):
    user = UserProfile.objects.get(user=request.user)
    user.followed_topics.remove(tag)
    user.save()
    return redirect('medium:tags', tag=tag)


@login_required
def add_cheer(request, pk):
    post = Post.objects.get(pk=pk)
    post.cheers.add(request.user)
    post.save()
    return redirect('medium:post', pk=pk)


@login_required
def remove_cheer(request, pk):
    post = Post.objects.get(pk=pk)
    post.cheers.remove(request.user)
    post.save()
    return redirect('medium:post', pk=pk)

medium/templates/medium/base.html
<!DOCTYPE html> {% load static %}
<!--
@File   : base.html
@Author :  ({__email})
@Link   : 
@Date   : 3/3/2018, 9:28:11 PM
-->
<html>

<head>
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
        crossorigin="anonymous">

    <!--<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css"
        media="screen" charset="utf-8">-->
    {% block head %} {% endblock %}

    <link rel="stylesheet" href="{% static 'medium/styles.css' %}">

</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container">
            <ul class="navbar-title">
                <a href="{% url 'medium:index' %}">
                    <svg class="svgIcon-use" width="138" height="27" viewBox="0 0 138 27">
                        <path d="M130 27V16.96c0-3.26-.154-5.472-2.437-5.472-1.16 0-2.138.57-2.863 1.512.217.906.3 1.968.3 3.127 0 2.247.036 5.11 0 7.973 0 .472-.046.58.244.87L127 27h-8V16.96c0-3.297-.461-5.472-2.708-5.472-1.16 0-1.64.653-2.292 1.595V24.1c0 .472-.026.58.3.87L116 27h-8V11.56c0-.47-.07-.579-.36-.905L106 9h8v3.612c.906-2.537 2.437-4.112 5.372-4.112 2.682 0 4.494 1.466 5.255 4.257.834-2.392 3.008-4.257 6.053-4.257 3.588 0 5.32 2.626 5.32 7.627 0 2.392.036 5.11 0 7.973 0 .472.004.652.25.87L138 27h-8zm-27-3.045c0 .472-.149.617.178.906L105 27h-8v-4c-.906 2.465-2.956 4-5.637 4C87.775 27 86 24.39 86 19.461c0-2.391-.036-5 0-7.936 0-.471-.11-.58-.4-.87L84 9h8v9.628c0 3.225.269 5.4 2.298 5.4 1.16 0 2.086-.725 2.702-1.63V11.56c0-.471-.129-.58-.419-.906L95 9h8v14.955zM78.002.25A3.248 3.248 0 0 1 81.25 3.5 3.25 3.25 0 1 1 78.002.25zM75 27V11.56c0-.47.168-.579-.122-.905L73 9h8v15.1c0 .472-.01.678.24.9L83 27h-8zM64 11.706c-.507-.652-1.418-1.123-2.396-1.123-1.957 0-3.842 1.775-3.842 7.03 0 4.93 1.631 6.669 3.66 6.669.907 0 1.853-.436 2.578-1.378V11.706zm6 12.286c0 .47-.026.58.3.87L72 27h-8v-3.697C62.913 25.804 60.951 27 58.632 27 54.5 27 51.5 23.738 51.5 17.795c0-5.582 3.254-9.314 7.784-9.314 2.356 0 3.919 1.123 4.716 2.899V3.878c0-.471-.077-.617-.403-.906L62 1.305 70 .29v23.702zM43.9 16c.037-.471.037-.67.037-.815 0-4.747-.937-5.435-2.437-5.435-1.5 0-2.854.995-2.927 6.25h5.328zm-5.327 1c0 4.711 2.392 6.63 5.183 6.63 2.174 0 4.313-.943 5.509-3.335h.072c-.942 4.566-3.77 6.705-8.01 6.705-4.566 0-8.879-2.755-8.879-9.133 0-6.705 4.277-9.386 9.097-9.386 3.842 0 7.937 1.811 7.937 7.646 0 .109 0 .438-.036.873H38.573zM31.5 27h-12l2.39-2.646c.084-.084.11-.399.11-.87V7l-7.866 20L5.581 8.372C5.364 7.9 5.181 7.285 5 6.777V20.62c0 .58-.035.653.364 1.196L9 27H0l3.64-5.183c.399-.543.36-.616.36-1.196V6.27c0-.617.095-.69-.195-1.051L1 1h8.495l7.355 16.3L23.24 1h8.26l-2.2 2.75c-.326.326-.3.599-.3 1.106v18.629c0 .47.005.75.138.87L31.5 27z"></path>
                    </svg>
                </a>
                <br> Made by iampeternguyen |
                <a href="https://github.com/iampeternguyen/medium-clone">source</a>

            </ul>
            <ul class="navbar-left">
                <!-- <button class="btn-nav btn-register">Upgrade</button> -->
                <form action="{% url 'medium:search' %}" method="get">
                    {% csrf_token %}
                    <input type="text" name="search" id="search" class="btn-nav" placeholder="Search">
                </form>
            </ul>



            <ul class="navbar-right">
                {% if user.is_authenticated %} {% if user.profile.avatar %}
                <a href="{% url 'medium:me' %}">
                    <img src="{{user.profile.avatar.url}}" class="nav-profile-img" width="25px" alt=""> </a>{%endif%}
                <a href="{% url 'medium:new' %}">&nbsp;
                    <span class="glyphicon glyphicon-plus"></span>
                </a>&nbsp;
                <a href="{% url 'medium:drafts' %}" class="welcome">
                    <span>drafts</span>
                </a>
                <a href="{% url 'medium:logout' %}">
                    <button class="btn-nav btn-register">Logout</button>
                </a>

                {% else %}
                <a href="{% url 'medium:login' %}" class="btn-login">Sign in</a>
                <a href="{% url 'medium:register' %}">
                    <button class="btn-nav btn-register">Get started</button>
                </a>
                {% endif %}

            </ul>
        </div>

    </nav>
    {% block featured %} {% endblock %}
    <div class="container">
        {% block content %} {% endblock %}

    </div>

    <script src="{% static 'medium/scripts.js' %}"></script>
</body>

</html>

medium/templates/medium/drafts.html
{% extends 'medium/base_paginated.html' %}{% load medium_extras %} {% block title %}
<h1>Drafts</h1> {% endblock %}

medium/templates/medium/index.html
{% extends 'medium/base_paginated.html' %} {% block title %}
<h1>Recent Posts</h1> {% endblock %}
<!-- -->
{% block sidebar %} {% if user.is_authenticated %}
<div class="panel panel-default">
    <div class="panel panel-head">
        {% if followed_posts %}
        <h2>Followed Posts</h2>
    </div>
    <div class="panel panel-body">
        {% for post in followed_posts %}
        <h4>
            <a href="{% url 'medium:post' pk=post.pk%}">{{post.title}}</a>
        </h4>
        <p class="text-muted">
            <a href="{% url 'medium:profile' pk=post.author.pk %}">{{post.author}}</a>
        </p>
        <p class="text-muted">
            {% for tag in post.tags.all %}
            <a href="{% url 'medium:tags' tag=tag %}">{{tag}}</a>
            {% empty %} {%endfor%}
        </p>
        <p>
            {{post.content|striptags|safe|truncatechars:300}}
        </p>
        {% endfor %} {% else %} Start following people or topics! {% endif %}

    </div>
    {% endif %}
</div>

{% endblock %}

medium/templates/medium/login.html
{% extends 'medium/base.html' %} {% block content %}
<h1>Login</h1>
<form action="{% url 'medium:login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username: </label>
    <input type="text" name="username" id="username">
    <label for="password">Password: </label>
    <input type="password" name="password" id="password">
    <button type="submit">Login</button>
</form>
{% endblock %}

medium/templates/medium/post.html
{% extends 'medium/base.html' %}{% load medium_extras %} {% block content %} {% if post.featured_image %}
<img id="featured" src="{{post.featured_image.url}}" alt="your image" />{% else %} {% endif %}
<h1>{{post.title}} {% if user.is_authenticated and post.author == user %}
    <!-- -->
    <span class="post-edit-publish-links">
        <a href="{% url 'medium:post_edit' pk=post.pk %}">Edit</a> |
        <a href="{% url 'medium:post_delete' pk=post.pk %}">Delete</a>

        {% if not post.published_date %} |
        <a href="{% url 'medium:post_publish' pk=post.pk %}">Publish</a>

    </span>{% endif %} {% endif %}</h1>

<p>by
    <a href="{% url 'medium:profile' pk=post.author.pk %}">{{post.author}}</a>
    <!-- -->
    {% if user.is_authenticated %} {% if post.author != user %}
    <!-- -->{% if post.author.pk|already_followed_user:user %}
    <!-- <-->
    <a href="{% url 'medium:unfollow_user' author_pk=post.author.pk post_pk=post.pk %}">Unfollow</a>
    </-->
    <!-- -->{% else %}
    <a href="{% url 'medium:follow_user' author_pk=post.author.pk post_pk=post.pk %}">Follow</a>
    <!-- -->{% endif %} {% endif %} {% else %} Login to follow {%endif%}
    <br>{% if post.published_date %} on {{post.published_date|date}}{% endif %}
</p>
<!-- -->

<div class="blog-tags">
    {% for tag in post.tags.all %}
    <a href="{% url 'medium:tags' tag=tag %}">{{tag}}</a>
    {% empty %} {%endfor%}
</div>
<div class="blog-body">
    {{post.content|safe}}
</div>
<div class="cheer">
    <p>
        {% if post.pk|already_cheered:user %}
        <a href="{% url 'medium:remove_cheer' pk=post.pk %}">
            {% else %}
            <a href="{% url 'medium:add_cheer' pk=post.pk %}"> {% endif %}
    </p>
    <span class="glyphicon glyphicon-hand-up larger" style="font-size:3em;"></span>
    </a>
    <span style="vertical-align:50%"> {{post.cheers.count}}
    </span>
</div>
<h2>Responses</h2> {% for comment in post.all_comments %}

<div class="panel panel-default comment-container">
    <div class="panel panel-head">
        <span class="comment-author">
            {{comment.author}}
        </span>
        <span class="comment-date"> {{comment.created_date|timesince}} ago</span>
        {% if user.is_authenticated and comment.author == user or post.author == user %}
        <span class="comment-delete">
            <a href="{% url 'medium:delete_comment' pk=comment.pk%}">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
        </span>
        {% endif %}

    </div>
    <div class="panel-body comment-content">
        {{comment.content}}
    </div>

</div>
{% empty %}
<p>Be the first to comment!</p>
{% endfor %} {% if user.is_authenticated %}
<div class="comment-form-container">
    <form method="post" action="{% url 'medium:add_comment' pk=post.pk%}" class="comment-form">
        {% csrf_token %}{% load crispy_forms_tags %} {{comment_form|crispy}}
        <button type="submit" class="btn btn-primary">Add Response</button>
    </form>
    {% else %} To comment, you must be a registered user.
    <a href="{% url 'medium:login' %}">Sign in</a> now or
    <a href="{% url 'medium:register' %}">
        create an account</a> to get started.
</div>
<br> {% endif %} {% endblock %}

medium/templates/medium/topic_list.html
{% extends 'medium/base_paginated.html' %}{% load medium_extras %} {% block title %}
<h1>{{tag}}</h1>
{% if user.is_authenticated %}
<!-- -->{% if tag|already_followed_topic:user %}
<!-- -->
<a href="{% url 'medium:unfollow_topic' tag=tag %}">Unfollow</a>
<!-- -->{% else %}
<a href="{% url 'medium:follow_topic' tag=tag %}">Follow</a>
<!-- -->{% endif %} {% else %} Login to follow {%endif%} {% endblock %}